name 'chef-mopidy'
maintainer 'Elijah Wright'
maintainer_email 'elijah.wright@gmail.com'
license 'all_rights'
description 'Installs/Configures chef-mopidy'
long_description 'Installs/Configures chef-mopidy'
version '0.1.0'
depends 'build-essential'
depends 'apt'
depends 'python'
depends 'yum'
